config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#show"
    resources :records do
      resources :receipts
    end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/receipt.rb
class Receipt < ApplicationRecord
    belongs_to :records
    belongs_to :users
end

app/models/record.rb
class Record < ApplicationRecord
    belongs_to :user
    mount_uploader :sleeve, SleeveUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :records
    has_many :receipts
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :location])
    end

end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def show
  end

  def new
  end

  def update
  end

  def create
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  private

  def record_params
    params.require(:record).permit(:record_label, :artist, :title, :year, :condition, :description, :user_id, :sleeve)
  end

public


  def show
    @record = Record.find(params[:id])
    @user = Record.find(params[:user_id])
  end

  def new
    @record = Record.new()
  end

  def index
    @records = Record.all
    @user = current_user
  end

  def query_all
    Record.where([ "record_label LIKE ? or artist LIKE ? or year LIKE ?", "%#{(params[:user_query])}%" , "%#{(params[:user_query])}%", "%#{(params[:user_query])}%" ]) 
  end


  def create
    record = params['record']
    current_user.records.create(record_params)
    flash[:sucess]=  'your record was added'
    redirect_to records_path
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to records_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
private 

  def user_params
    params.require(:user).permit(:username,:records,:location, :email)
  end


public

  def show
    @user = current_user
    @record = Record.new()
  end

  def new
    @user = User.new()
  end

  def index
    @users = User.all
  end

  def create

      @user = current_user
      flash[:sucess]=  'your user was created'
      # redirect_to user_path(@user)
     end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def home
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bopshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application',  media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= link_to "log out", destroy_user_session_path, method: :delete%>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/receipts/create.html.erb
<h1>Receipts#create</h1>
<p>Find me in app/views/receipts/create.html.erb</p>

app/views/receipts/new.html.erb
<h1>Receipts#new</h1>
<p>Find me in app/views/receipts/new.html.erb</p>

app/views/receipts/show.html.erb
<h1>Receipts#show</h1>
<p>Find me in app/views/receipts/show.html.erb</p>

app/views/receipts/update.html.erb
<h1>Receipts#update</h1>
<p>Find me in app/views/receipts/update.html.erb</p>

app/views/records/create.html.erb
<h1>Records#create</h1>
<p>Find me in app/views/records/create.html.erb</p>

app/views/records/index.html.erb
<h1>Records</h1>

<%= link_to "home", root_path%>

 <% @records.each do |record| %>
  
  <div class="card-body">
  <%= link_to "Remove", record_path(record), method: :delete%>
   <p class="card-text">record label: <%= record.record_label%>artist: <%= record.artist%>
  title: <%= record.title%> year <%= record.year%> condition: <%= record.condition%>
  description <%= record.description%></p>
   </div>
  </div>
    <% end %>
    

                  

app/views/records/new.html.erb
<h1>Records#new</h1>
<p>Find me in app/views/records/new.html.erb</p>

app/views/records/show.html.erb
<h1>Records#show</h1>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>boPshoP</h1>
<%= form_for @user do |form| %>
Username: <%= form.text_field :username%><br />
Location: <%= form.text_field :location%><br />
   Email: <%= form.text_field :email%><br /> 
   <%= form.submit 'Sign Up' %>
	    <% end %>

app/views/users/show.html.erb
<h1 class= "welcome"> </h1>


<div>Email: <%=@user.email %></div>

<div>Username: <%= @user.username %></div>
<div>Location: <%= @user.location %></div>

 

		<div class="card" style="width: 18rem;">
			<div class="card-body">
			  <h5 class="card-title">Sell a Record</h5>
			  <%= form_for @record do |form| %>

			  <p class="card-text">
				<p>record label: <%= form.text_field :record_label%><br /></p>
				<p>artist: <%= form.text_field :artist%><br /></p>
				<p>title: <%= form.text_field :title%><br /></p>
				<p>
				year: <%= form.text_field :year%><br />
				</p>
				condition: <%= form.text_field :condition%><br />
				description: <%= form.text_field :description%><br />
				record sleeve: <%= form.file_field :sleeve %><br />
			<%= form.submit 'Post Record' %>
			</p>
			<% end %> -->

			  <a href="#" class="btn btn-primary">Go somewhere</a>
			</div>
		  </div>

		

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>